# Generated by Django 3.2.6 on 2022-07-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=64, unique=True)),
                ('complexity', models.IntegerField(default=None)),
                ('accepted', models.BigIntegerField(default=None)),
                ('attempts', models.BigIntegerField(default=None)),
                ('condition', models.TextField(max_length=1024)),
                ('answer', models.FloatField()),
            ],
            options={
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('problems', models.ManyToManyField(related_name='tags', to='topics.Problem')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_topics', to='topics.topic')),
            ],
            options={
                'db_table': 'subtopic',
            },
        ),
        migrations.CreateModel(
            name='ProblemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image_link', upload_to='images/')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='topics.problem')),
            ],
            options={
                'db_table': 'problem_image',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='sub_topics',
            field=models.ManyToManyField(related_name='problems', to='topics.Subtopic'),
        ),
    ]
