# Generated by Django 3.2.6 on 2021-08-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='subtopic',
            new_name='sub_topic',
        ),
    ]
