# Generated by Django 3.2.6 on 2021-08-25 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_rename_tags_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='problem',
            name='sub_topics',
            field=models.ManyToManyField(related_name='problems', to='topics.Subtopic'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='topics.topic'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='problems',
            field=models.ManyToManyField(related_name='tags', to='topics.Problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='topics.task'),
            preserve_default=False,
        ),
    ]
