# Generated by Django 3.2.6 on 2021-08-25 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_auto_20210825_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='accepted',
            field=models.BigIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='attempts',
            field=models.BigIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='complexity',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
