# Generated by Django 3.2.6 on 2021-08-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_auto_20210825_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='complexity',
        ),
    ]
