# Generated by Django 3.2.6 on 2021-08-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_auto_20210825_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='task',
        ),
    ]
