# Generated by Django 3.2.6 on 2021-08-25 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0010_remove_problem_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='task',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
