# Generated by Django 3.2.6 on 2021-08-25 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0011_problem_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='accepted',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='attempts',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='complexity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='problem',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='topics.task'),
            preserve_default=False,
        ),
    ]
