# Generated by Django 3.2.6 on 2021-08-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0012_auto_20210825_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem',
        ),
        migrations.AddField(
            model_name='task',
            name='problem',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related', to='topics.problem'),
            preserve_default=False,
        ),
    ]
