# Generated by Django 3.2.6 on 2021-08-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0017_alter_task_problem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
