# Generated by Django 3.2.6 on 2021-09-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0020_alter_task_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='images',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
