# Generated by Django 3.2.6 on 2021-11-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0021_problem_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='images',
        ),
        migrations.CreateModel(
            name='ProblemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default=None, upload_to='images/')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_image', to='topics.problem')),
            ],
        ),
    ]
