# Generated by Django 3.2.6 on 2021-12-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0022_auto_20211127_0013'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='problemimage',
            table='ProblemImage',
        ),
    ]
