# Generated by Django 3.2.6 on 2021-12-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0023_alter_problemimage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='problem',
            table='problem',
        ),
        migrations.AlterModelTable(
            name='problemimage',
            table='problem_image',
        ),
        migrations.AlterModelTable(
            name='subtopic',
            table='subtopic',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
