# Generated by Django 3.2.6 on 2021-12-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0024_auto_20211214_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='condition',
            field=models.TextField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='task',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
