# Generated by Django 3.2.6 on 2021-12-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0025_auto_20211214_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='task',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
