# Generated by Django 3.2.6 on 2021-12-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0026_auto_20211214_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemimage',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
