# Generated by Django 3.2.6 on 2021-12-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0027_alter_problemimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problemimage',
            name='images',
            field=models.ImageField(default='image_link', upload_to='images/'),
        ),
    ]
