# Generated by Django 3.2.6 on 2021-12-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0028_auto_20211214_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemimage',
            old_name='images',
            new_name='image',
        ),
    ]
