# Generated by Django 3.2.6 on 2021-12-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0029_rename_images_problemimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemimage',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='topics.problem'),
        ),
    ]
