# Generated by Django 3.2.6 on 2021-12-29 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0030_alter_problemimage_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='condition',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='problem',
            name='task',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='problemimage',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='topics.problem'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_topics', to='topics.topic'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
