# Generated by Django 3.2.6 on 2022-01-20 17:35

from django.db import migrations, models
import misc.validators


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0032_auto_20220120_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.FloatField(),
        ),
    ]
