# Generated by Django 3.2.6 on 2022-01-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0033_alter_problem_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='task',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
