# Generated by Django 3.2.6 on 2022-01-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0034_alter_problem_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='task',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
