# Generated by Django 3.2.6 on 2022-07-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('problems', models.ManyToManyField(related_name='tags', to='problems.Problem')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
