# Generated by Django 3.2.6 on 2022-07-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topics.problem')),
            ],
            options={
                'db_table': 'problem_test',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('problem', models.ManyToManyField(through='tests.ProblemTest', to='topics.Problem')),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='UserProfileTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=None)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile')),
            ],
            options={
                'db_table': 'test_user_profile',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('test_time', models.DateTimeField(auto_now_add=True)),
                ('problems_info', models.JSONField()),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_tests', to='profiles.userprofile')),
            ],
            options={
                'db_table': 'test_result',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='user_profile',
            field=models.ManyToManyField(through='tests.UserProfileTest', to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='problemtest',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test'),
        ),
    ]
