# Generated by Django 3.2.6 on 2021-12-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_userprofile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='UserProfileTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=None)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='user_profile',
            field=models.ManyToManyField(through='tests.UserProfileTest', to='users.UserProfile'),
        ),
    ]
