# Generated by Django 3.2.6 on 2021-12-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofiletest',
            table='test_user_profile',
        ),
    ]
