# Generated by Django 3.2.6 on 2021-12-29 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0031_auto_20211229_1746'),
        ('tests', '0002_alter_userprofiletest_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topics.problem')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test')),
            ],
            options={
                'db_table': 'problem_test',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='problem',
            field=models.ManyToManyField(through='tests.ProblemTest', to='topics.Problem'),
        ),
    ]
