# Generated by Django 3.2.6 on 2022-01-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211229_1746'),
        ('tests', '0003_auto_20211229_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('full_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_tests', to='users.userprofile')),
            ],
        ),
    ]
