# Generated by Django 3.2.6 on 2022-01-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20220112_1650'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testresult',
            table='test_result',
        ),
    ]
