# Generated by Django 3.2.6 on 2022-01-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_testresult_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='full_info',
            new_name='user_profile',
        ),
    ]
