# Generated by Django 3.2.6 on 2022-01-12 15:15
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_rename_full_info_testresult_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
