# Generated by Django 3.2.6 on 2022-01-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_testresult_test_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtest',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
