# Generated by Django 3.2.6 on 2022-01-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_problemtest_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='problems_info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresult',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
